### ISSUE TITLE
Admendments to IDS containing 虚/虛 for Extension B and up

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#1]
> U+25CA4   𥲤    ⿱竹虚
> U+271FA   𧇺    ⿰光虛
> U+27754   𧝔    ⿰衤虚[G]    ⿰衤虛[T](control comparison)
> U+27D06   𧴆    ⿰豸虛
> U+28F0B   𨼋    ⿰阝虛
> U+293E3   𩏣    ⿰虛韋
> U+2955A   𩕚    ⿰虛頁
> U+2B8DE   𫣞    ⿰亻虛

can be changed to:

> U+25CA4   𥲤    ⿱竹虚[G]    ⿰竹虚[TH]
> U+271FA   𧇺    ⿰光虚[G]    ⿰光虚[X]
> U+27754   𧝔    ⿰衤虚[G]    ⿰衤虛[T](control comparison)
> U+27D06   𧴆    ⿰豸虚[G]    ⿰豸虛[T]
> U+28F0B   𨼋    ⿰阝虚[G]    ⿰阝虛[TV]
> U+293E3   𩏣    ⿰虚韋[G]    ⿰虛韋[T]
> U+2955A   𩕚    ⿰虛頁[T]    ⿰虚頁[X]
> U+2B8DE   𫣞    ⿰亻虛[V]    ⿰亻虚[X]

**Comment by hfhchan** [comment]
Thank you for the correction in the main file. However there is still one bug:

> U+271FA   𧇺    ⿰光虛

should be 

> U+271FA   𧇺    ⿰光虚

Thanks!

**Comment by kawabata** [comment]
Sorry for late reply.  I will fix it in next release.

**Comment by kawabata** [comment]
fix confirmed and issue closed.
