### ISSUE TITLE
U+2C606

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#11]
U+2C606	𬘆	⿰ 糹 ⿻ 申 ⿱ 𠔽 月 ⿰ 糹 ⑭

should be 

    U+2C606	𬘆	⿰ 糹𤲥

instead.

Reference:

    U+2A9A7	𪦧	⿰ 女 𤲥

**Comment by kawabata** [comment]
as 𤲥 is 13 strokes, but non-radical strokes of 𪦧 is 14, I modified a bit from your proposal.  Thanks!
