### ISSUE TITLE
U+2298F

### ISSUE THREAD

**Issue by benkasminbullock** [cjkvi/cjkvi-ids#111]
The ⿶ in the following decomposition seems possibly wrong since there is no part of 戈 to the left of the 十:

U+2298F	𢦏	⿶戈十

But there is  ⿸  and  ⿹  and  ⿺ but no "top left corner" element, so perhaps the ⿶ is some kind of workaround? Or should this be ⿻?

**Comment by hfhchan** [comment]
@eisoch

**Comment by hfhchan** [comment]
Top left corner IDS is not coded yet. I think China had a proposal to add them.

**Comment by benkasminbullock** [comment]
Also 

U+38A4	㢤	⿹⿶弋十⿰丿𠃌
U+6220	戠	⿹⿶戈⿱亠丷日[G]	⿰音戈[TJK]
U+6B66	武	⿹⿶弋一止
U+8CAE	貮	⿹⿶弋一貝

so this is clearly intentional rather than being a mistake. Anyway I'll close this one, since it seems there are enough unresolved issues here and the maintainer hasn't been seen here for over two years.
