### ISSUE TITLE
U+205B8	𠖸

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#12]
U+205B8	𠖸	⿰ 冫 ⿱ &CDP-8AFC;() 匕

is actually

    U+205B8	𠖸	⿰冫仺

By etymology,
仺 = 倉
𠖸 = 滄

Therefore, the separation of strokes and the presence of final 鉤 need not be counted as different component.

**Comment by hfhchan** [comment]
Similar case

    U+206DB	𠛛	⿰ ⿱ &CDP-8AFC;() 匕 刂

to

    U+206DB	𠛛	⿰仺刂

**Comment by kawabata** [comment]
Thanks.  
I've added the additional decomposition patterns for these entries.

**Comment by kawabata** [comment]
fixed confirmed.
