### ISSUE TITLE
No japanese decomposition for 肌

### ISSUE THREAD

**Issue by glandium** [cjkvi/cjkvi-ids#15]
The database contains:
```
U+808C  肌      ⿰月几[GTV]     ⿰⺼几[T]
```
The character is a japanese 常用漢字, and should have a japanese decomposition, which would likely be the former. The are other characters around this one that have the same kind of decompositions, where both side have a T decomposition, but no J. I wonder if they are typos, or if both decompositions actually are valid for T.

**Comment by hfhchan** [comment]
U+808C  肌      ⿰月几[GTV]     ⿰⺼几[T]

should read

U+808C  肌      ⿰月几[GJV]     ⿰⺼几[T]

**Comment by hfhchan** [comment]
The compositions are supposed to follow the UCS code charts.  When they don't, they are usually errors.  This one is just a random typo.

**Comment by kawabata** [comment]
Thanks.  I will fix this in next release.

**Comment by kawabata** [comment]
Now fixed.  Sorry for late response.
