### ISSUE TITLE
Amendment to IDS

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#2]
> U+7690    皐 ⿱白𠦂

is more correctly

> U+7690    皐 ⿱白𠦂[GHV] ⿱白⿻十⿰二二[TJK]

This does not affect any character containing U+7690, except for the following.

> U+22FCE   𢿎    ⿰皐攴

The T-source of this character the last stroke on the left bends leftwards.

**Comment by kawabata** [comment]
I'm sorry that I was late on response.
I've checked the newest version of UCS and
reflected most of your proposed changes.

Regards,

On Thu, Mar 5, 2015 at 2:30 PM, hfhchan notifications@github.com wrote:

> U+7690 皐 ⿱白𠦂
> 
> is more correctly
> 
> U+7690 皐 ⿱白𠦂[GHV] ⿱白⿻十⿰二二[TJK]
> 
> This does not affect any character containing U+7690, except for the
> following.
> 
> U+22FCE 𢿎 ⿰皐攴
> 
> The T-source of this character the last stroke on the left bends leftwards.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cjkvi/cjkvi-ids/issues/2.

## 

---

川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by hfhchan** [comment]
Thanks!
