### ISSUE TITLE
Decomposition for 祈 and 祉

### ISSUE THREAD

**Issue by glandium** [cjkvi/cjkvi-ids#20]
They are:
```
U+7948	祈	⿰礻斤[GT]	⿰示斤[JK]
U+7949	祉	⿰礻止[GT]	⿰示止[JK]
```

I think they should be:
```
U+7948	祈	⿰礻斤[GTJ]	⿰示斤[K]
U+7949	祉	⿰礻止[GTJ]	⿰示止[K]
```

The reason is that while there are 旧字体 with the 示 form, their form in the 常用漢字表 is with 礻.
Plus, the variants with 示 now have their own codepoints: U+FA4E (祈) and U+FA4D (祉)

**Comment by kawabata** [comment]
I fixed it.  Thanks for the report and sorry for late reply.
