### ISSUE TITLE
Decomposition for 雨

### ISSUE THREAD

**Issue by laughedelic** [cjkvi/cjkvi-ids#22]
Hi. I'm not sure that this is the right place to report this. I was using Atom [factoids](https://github.com/mashabow/factoids) plugin (which uses the data from this repo) and noticed that 雨 is decomposed as `⿱一𠕒` and this looks very strange to me. 
I'm not a specialist in this stuff, so probably it's correct.

**Comment by kawabata** [comment]
Semantically, you may be right.  This is purely a decomposition based on non-semantic shape-only basis, so many of the decomposition may look strange.  If you believe this is a pure mistake, please let me know.
