### ISSUE TITLE
Consider using U+31E3 in U+3514 㔔, U+3AB3 㪳 & U+3AC8 㫈

### ISSUE THREAD

**Issue by kenlunde** [cjkvi/cjkvi-ids#24]
The IDSes for U+3514 㔔, U+3AB3 㪳, and U+3AC8 㫈 use U+3007 〇 as its component, but U+3007 has numeric properties, and is suitable as a component only in shape.

Instead, consider replacing it with CJK Stroke U+31E3, which has no numeric properties, and corresponds to a syllable-final _ng_/_ŋ_ sound that is related to the shape of U+11BC HANGUL JONGSEONG IEUNG (combining) or U+3147 ㅇ HANGUL LETTER IEUNG (compatibility).

**Comment by kawabata** [comment]
Thank you for valuable comments.
Will be fixed in next release.
