### ISSUE TITLE
Decomposition of U+2189B

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#25]
U+2189B	𡢛	⿱⿲幺⿱丿幺幺𡚴[G]	⿱𪺕𡚴[T]

should be changed to 

    U+2189B	𡢛	⿱⿲幺⿱丿幺幺𡚴[G]	⿳丿⿲幺幺幺𡚴[T]

**Comment by kawabata** [comment]
Thanks for notifying me a mistake!
Now fixed it.
