### ISSUE TITLE
Decomposition for U+5FF9

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#26]
U+5FF9	忹	⿰忄王[G]	⿰忄壬[T]

should be 

    U+5FF9	忹	⿰忄王

**Comment by kawabata** [comment]
![05ff9](https://user-images.githubusercontent.com/217020/29060345-61062f46-7c54-11e7-9d35-ade768bd016f.png)

I will move this to [O] tag.

**Comment by hfhchan** [comment]
I think they were disunified in the early 2000s...

**Comment by kawabata** [comment]
Yup, but it is impossible to update all existing encoded texts, I think disunification should be strongly discouraged and be recorded... (cf. Annex J of PnP of JTC1/SC2/WG2 "Guideline for correction of CJK ideograph mapping table errors")
