### ISSUE TITLE
Decomposition for U+9269 鉩 

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#27]
U+9269	鉩	⿰金尒[GJK]  ⿰金𡭗[T]

should be 

    U+9269	鉩	⿰金尒

**Comment by kawabata** [comment]
Before its glyph is altered, it has been in the standard for more than 20 years,
and people rarely refer the newest standards when they use the character.  I will move
this to [O] tags.
 
![09269](https://user-images.githubusercontent.com/217020/29060256-f4defd84-7c53-11e7-909a-e6b009a9b88a.png)
