### ISSUE TITLE
U+20CB9 𠲹

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#28]
Add `⿰口忌`

**Comment by kawabata** [comment]
Thanks!
this entry will be changed to:
U+20CB9	𠲹	⿱𠯇心[UV]	⿰口忌[GT]

**Comment by kenlunde** [comment]
Based on the current _ids.txt_, I think that this issue can be closed.

**Comment by kawabata** [comment]
Closing issue.
