### ISSUE TITLE
 U+443D	䐽

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#30]
U+443D  䐽  ⿰⺼⿱廿兩[T]  ⿰月⿱廿兩[K]  ⿰月㒼[X]

to

    U+443D  䐽  ⿰月⿱㒼[G]  ⿰⺼⿱㒼[T]  ⿰月⿱廿兩[K]

**Comment by kawabata** [comment]
Thank you.
Updated the file.  There had been no G-column entry for U+443D in older version of UCS,
but only Ariel Unicode font equipped with Windows OS has this shape, so I added it as eXtra.
But it seems G-column has been added in recent version of the UCS.
