### ISSUE TITLE
U+5DEB 巫 

### ISSUE THREAD

**Issue by kenlunde** [cjkvi/cjkvi-ids#31]
Wouldn't ⿻工从 be a better or more intuitive IDS for U+5DEB 巫 than ⿱一⿻丄从? For reference, Table I.1 of ISO/IEC 10646 Annex I uses ⿻从工 as the example IDS for U+2FFB ⿻, though I feel that ⿻工从 is more intuitive.

**Comment by kawabata** [comment]
Sure.
For my policy, IDS should be both intuitive and easy to vertically/horizontally decomposable,
in case it was embedded into other character as DC.

I've updated the IDS data.
