### ISSUE TITLE
How do you prefer users to Quote your work?

### ISSUE THREAD

**Issue by LinguList** [cjkvi/cjkvi-ids#32]
I am a big fan of this library and I have been using it for personal purposes a lot, but I am considering using small parts of the data in a paper to illustrate how Chinese character evolution could be modeled. I could quote this library by just passing the github link, however, I'd prefer if you share how you like to be quoted explicitly, so that you get the credit you deserve. Furthermore, I'd suggest that you make a release of the data, and that you also submit this release to some open repository like Zenodo.org, so that we can quote you correctly, with a DOI for a particular version that is being used in research (non-profit, of course).

**Comment by kawabata** [comment]
Thank you for your comment and recommendation of zenodo.org, and I'm sorry for the late reply.
I've just browsed the zenodo feature, released my repository, and get the first DOI badge as follows:

[![DOI](https://zenodo.org/badge/1788781.svg)](https://zenodo.org/badge/latestdoi/1788781)

I hope this helps you.

**Comment by LinguList** [comment]
I did a bit of digging to be able to quote your name. In BibTex, I quoted you now like this:

```bibtex
@Online{Kawabata2014,
  author       = {Kawabata, Taichi},
  title        = {Ideographic Description Sequence Data},
  year         = {2014},
  url          = {https://github.com/cjkvi/cjkvi-ids},
  note         = {The project provides data on CJK ideographs in various forms.},
  organisation = {CHISE},
}
```
I mention this database in a paper which you can find here: http://lingulist.de/documents/papers/list-2018-network-approaches-yinyunxue.pdf It's a draft, so I can revise if you have suggestions. And I'll also add the DOI. Thanks a lot to everybody contributing here for your great work!

**Comment by kawabata** [comment]
Thanks for your making bibtex data, but I'm not currently affiliated with CHISE group.  (This data is indeed derived from CHISE database, though.)

Your paper is quite interesting, perhaps other Japanese github repositories might be interest of you, e.g. https://github.com/shikeda/HDIC.

Regards,

**Comment by LinguList** [comment]
Okay, thanks, this is exactly, why I wanted to share it, I'll revise it accordingly (I'm sure will quote you more in the future, and also include it in the revision of the draft):

```bibtex
@Online{Kawabata2014,
  author       = {Kawabata, Taichi},
  title        = {Ideographic Description Sequence Data},
  year         = {2014},
  url          = {https://github.com/cjkvi/cjkvi-ids},
  note         = {The project provides data on CJK ideographs in various forms.},
}
```

**Comment by kawabata** [comment]
Thanks a lot for this suggestion!
