### ISSUE TITLE
Additional IDS for U+22001 𢀁

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#36]
> U+22001	𢀁	⿰𣧄犮

Based on the original sources of U+22001 (T5-3776) (http://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QzAzMDMx):

字彙:
![image](https://user-images.githubusercontent.com/8191296/35241030-23c91fec-fff0-11e7-8135-c10678442e29.png)

重訂直音篇:
![image](https://user-images.githubusercontent.com/8191296/35241040-2d77dec0-fff0-11e7-856d-e020f44f4a43.png)

𢀁 Pronunciation 魚乞切
𣧄 Pronunciation 魚乙切 / 魚乞切.

**Comment by kawabata** [comment]
pursuasive.  added.  thanks!
