### ISSUE TITLE
IDS for U+43D5 䏕

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#38]
> U+43D5    䏕    ⿰月𡈼[G] ⿰⺼壬[T] ⿰月王[J] ⿰月壬[K]

should be changed to

> U+43D5    䏕    ⿰月壬[GK] ⿰⺼𡈼[T] ⿰月王[J]

Also to say, the ⿰月王 glyph for Japan looks very suspicious (according to IPA 文字情報基盤, the pronunciation of the two unified variants are different), and that the TF glyph (⿰⺼𡈼) has displaced the more correct T4 glyph (⿰⺼壬) which is now in U+2F981.

**Comment by kawabata** [comment]
Yes.  J-form unification is somewhat unfortunate.
Fixed as your comment.  Thanks!
