### ISSUE TITLE
Change to IDS U+2378C	𣞌

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#4]
```
U+2378C 𣞌    ⿰木⿱⿱白冖⿱太万
```

Should be

```
U+2378C 𣞌    ⿰木⿱⿱白冖⿱大方
```

This is evident with the T-source glyph (TF-5F2D).  In T-source glyphs containing 太, the dot is always joined with 大. Also, for glyphs containing 方, the dot is always joined with 万.  In this case since the dot is joined with 万, it can be deducted that the correct decomposition is 大方.

This is also reflected in CNS11643's decomposition at
http://www.cns11643.gov.tw/AIDB/query_general_view.do?page=f&code=5f2d:
木白冖大亠&cdp-8b6c

**Comment by kawabata** [comment]
Thanaks for your bug report.
Fix has been committed.

Regards,
