### ISSUE TITLE
Merge all 朩 entries into 木

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#40]
朩 is an Idu character which is actually the cursive form of 木, so they are semantically equivalent from a CJK Unified Ideographs point of view.  Also, characters with 木 in Taiwan are usually written as 朩 without the hook when placed at the bottom.  Separating them causes difficulty in lookup.

Suggested Options:
(1) Merge all 朩 without the hook into 木.
(2) Merge all 朩 with or without the hook into 木.

I prefer Option (1), because Option (2) may confuse users in China.

---

If no change is made, then the following rules should be added:

| a | b | c |
| --- | --- | --- |
| U+409E | 䂞 | ⿱石木 [G] |
| U+202D5 | 𠋕 | ⿰亻⿱⿰工几木 [G] |

**Comment by kawabata** [comment]
Thanks for the comment.  Sometimes, a hook plays a significant semantic difference (such as 干 vs. 于), sometimes not.  My intention for separating 木 vs. 朩 is to show the local differences on position-dependent nature, and I believe if they can be considered equivalent and processed as so, it wouldn't confuse during processing.  So unless there is some persuasive reasoning for not separating them, I would like to leave as it is.  (And there are sometimes some indeed semantic differences, though not explicit, in case of "保", for example.)

So, I will add 409E and 202D5 an extra shape.  Thanks for the comment.

**Comment by hfhchan** [comment]
The characters which are currently quoted as "朩" actually have no hook, but "朩" has.  This may be a bit confusing for Traditional Chinese users. At least, to me, the presence of hook or not is more significant compared to the joining of the strokes representing the tree root.
