### ISSUE TITLE
Update U+4C8A  䲊

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#41]
> U+4C8A 䲊 ⿲魚卩&CDP-8CA9;[G] ⿰魚隋[T]

to

> U+4C8A 䲊 ⿰魚隋

**Comment by hfhchan** [comment]
![image](https://user-images.githubusercontent.com/8191296/36353317-0cc9d4f6-1500-11e8-84e9-85b4ff558be3.png)

**Comment by kawabata** [comment]
I don't know when its G shape was changed, but as it has long been a described shape, I will move it to "obsolete" flag.

![4c8a](https://user-images.githubusercontent.com/217020/36414047-28746c74-1664-11e8-8caa-2d4806e13d1d.png)
