### ISSUE TITLE
Update 𤚌 (U+2468C)

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#42]
![image](https://user-images.githubusercontent.com/8191296/36394742-94ca8ba2-15f0-11e8-9cff-c7360f51bdd4.png)

> U+2468C 𤚌 ⿸尸⿱⿰二⿺乚二牛

to

> U+2468C 𤚌 ⿸㞑牛

Also refer to:
![image](https://user-images.githubusercontent.com/8191296/36394749-99672db4-15f0-11e8-96fa-0f1c57ac49a1.png)
> U+21CB6 𡲶 ⿸㞑出

**Comment by kawabata** [comment]
Thanks for finding!.  I'll change it in next version.
