### ISSUE TITLE
𪼘 U+2AF18

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#48]
>U+2AF18 𪼘 ⿰王⿱𫇦亘

should be

> U+2AF18 𪼘 ⿰王萱

**Comment by kawabata** [comment]
These are different (⿱𫇦亘 vs. ⿱艹宣), aren't they?

**Comment by hfhchan** [comment]
Oh sorry, my bad.

BTW, it may be better to add as ⿰王萱[X], because the pronunciation of TD-6D3D is xuān, and that 宣 (U+5BA3) can often be written as 𭁴 (U+2D074), so it is quite sure that the right hand side is phonetic from 萱.

**Comment by hfhchan** [comment]
To say, 𪻭 (U+2AEED) = 瑄 (U+7444) and 𮘙 (U+2E619) = 諠 (U+8AE0) also.

**Comment by kawabata** [comment]
Yup.  Unfortunately, it wasn't separately encoded, but I think this may be worth discussion on IRG in future.  I will attach [X] as tentatively.
