### ISSUE TITLE
IDS for 騺

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#5]
> U+9A3A    騺 ⿱執馬[GT]   ⿱埶馬[K]

would now be

> U+9A3A    騺 ⿱執馬

in the latest code charts.

**Comment by kawabata** [comment]
As this pattern exists more than decade in the standard (until 2012), I'll leave it just for the record to avoid implementation confusion.

**Comment by kawabata** [comment]
I attached [O] tag (obsolete) for ⿱埶馬.
