### ISSUE TITLE
Additional IDS for 𠄚 (U+2011A)

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#50]
Suggest add IDS for U+2011A 𠄚 ⿰𠀭丁[X]

𠄚 in Kangxi:
![image](https://user-images.githubusercontent.com/8191296/38350496-1ca8e630-38de-11e8-909c-b6bdc6e63bbb.png)

𠄚 in Jiyun:
![image](https://user-images.githubusercontent.com/8191296/38350594-8442b9e2-38de-11e8-818b-4ae0569b72a0.png)

It is likely that Kangxi mis-copied the form again. 𠀭 is old form of 平, and based on the description of Kangxi and the arrangement of 𠄚 in Jiyun, 𠄚 is likely old form of 𢆊, so the left hand side should theoretically be 𠀭.

**Comment by kawabata** [comment]
Thanks.  I've added it as an eXtra part.
