### ISSUE TITLE
𫋑 U+2B2D1

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#51]
```
U+2B2D1	𫋑	⿰虫⿲王㐅王
```
should be changed to
```
U+2B2D1	𫋑	⿰虫班
```

Reference:
<img width="546" alt="screen shot 2018-04-15 at 3 39 17 pm" src="https://user-images.githubusercontent.com/3607926/38776049-3ebbb71a-40c3-11e8-99a4-50a8c4b4761b.png">

The 𫋑 has a semantic component 虫 and phono component 班.

**Comment by kawabata** [comment]
Thanks.  I've added it as an extra part.
