### ISSUE TITLE
Decomposition for 𡳲 U+21CF2

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#52]
U+21CF2 | 𡳲 | ⿺尾⿱爫萬

should be

U+21CF2 | 𡳲 | ⿺尾⿱爫禺

**Comment by hfhchan** [comment]
![image](https://user-images.githubusercontent.com/8191296/39395354-4ccaa008-4b10-11e8-974e-806caf50fd88.png)

**Comment by kawabata** [comment]
Thanks for finding the bug!  I've fixed it.
It's a bit weird character...

![3](https://user-images.githubusercontent.com/217020/39421129-970f5972-4ca2-11e8-9369-abbe68484aee.PNG)
