### ISSUE TITLE
𢿄 U+22FC4 and 𥼋 U+25F0B

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#56]
I doubt 𢿄 U+22FC4 shall be
```
⿱⿰未攵正
```

Also 𥼋 U+25F0B shall be
```
⿱⿰未攵𠩕
```

However I can't find K4 and GHC sources for further support, it is my guess from the shape of 10.0 code chart.

**Comment by kawabata** [comment]
Thanks.  I've confirmed them.  Fixed.
