### ISSUE TITLE
U+2502E	𥀮 - Add G-source Decomposition

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#58]
```
U+2502E	𥀮	⿲月⿱巛囪皮
```
should be
```
U+2502E	𥀮	⿲月⿱巛囪皮[U]	⿰腦皮[G]
```

**Comment by kawabata** [comment]
Thanks.  it seems G-source shape has been changed several years ago...

![capture](https://user-images.githubusercontent.com/217020/40061433-e8fe1226-5893-11e8-9735-0c4d15129d4b.png)
