### ISSUE TITLE
IDS for 䢄

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#6]
By etymology, according to 説文解字, it should be a top/bottom character, not left right.
Suggested change:
⿱辝林   ⿱辝𣏟[X]

**Comment by hfhchan** [comment]
By etymology,
U+67B2  枲 ⿱厶呆   ⿱台木
would also become
U+67B2  枲 ⿱厶呆   ⿱台木   ⿱台𣎳[X]

**Comment by kawabata** [comment]
I'll fix them in the next release

**Comment by kawabata** [comment]
fix confirmed, issue closed.
