### ISSUE TITLE
U+28C7D 𨱽 ⿰镸曳

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#60]
U+28C7D 𨱽 ⿰镸曳

U+28C7D 𨱽 ⿰長曳

**Comment by kawabata** [comment]
Thanks.  It seems it had been changed later.  fixed.

![5](https://user-images.githubusercontent.com/217020/40520932-c7010e40-6003-11e8-9ff8-5442239a4fa7.PNG)
