### ISSUE TITLE
U+2459B 𤖛

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#61]
```
U+2459B	𤖛	⿱將旦
```
should be
```
U+2459B	𤖛	⿱將且
```

Evidence:
![301175](https://user-images.githubusercontent.com/3607926/40307199-189b0436-5d34-11e8-8065-ec1b26c5e0c3.png)
![1103099](https://user-images.githubusercontent.com/3607926/40307200-18f50fc6-5d34-11e8-8f23-1ebaf16ea3bf.png)

**Comment by kawabata** [comment]
Yup.  Only T source follows the Kangxi shape.  Fixed, thanks.
