### ISSUE TITLE
U+234A6	𣒦	⿰木㑑

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#62]
```
U+234A6	𣒦	⿰木㑑
```
should be
```
U+234A6	𣒦	⿰木𪜮
```

See [CNS11643 Page](http://www.cns11643.gov.tw/AIDB/query_general_view.do?page=f&code=3565).

**Comment by kawabata** [comment]
Confirmed and fixed.  Wow, it should be very difficult to find!  Thanks!
