### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by tony** [cjkvi/cjkvi-ids#65]
Hi there!

I maintain a project dedicated to making CJK data available in a consistent way. I keep it at https://github.com/cihai

I've found your project through https://github.com/amake/cjk-decomp/commit/325e5ba2d4166a35ce5cf8cec4f3a9802204a0d6.

I find this data useful because I'm trying to recreate functionality similar to cjklib's decomposition information.

I am wondering what's the purpose behind GPL for datasets? GPL is a very noble license, I like it, but I don't know if it's written with data sets in mind. In fact, I'm more in favor of datasets being available openly as possible.

Is it possible to make this and similar data under something like a [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) type license? Or at the very minimum, something that doesn't have legal clauses that create derivative works? (It's probably unlikely someone is going to improve a project and not give back - they lose out on upstream contributions and have to resolve merge conflicts for a long time 😄)

I wrote a bit about this subject before in 2014 here: https://github.com/cihai/attic-cihai-handbook/blob/master/information_liberation.rst

I also talked a bit about CJK datasets and licensing before on the cjklib project's issues: https://github.com/cburgmer/cjklib/issues/6

**Comment by laughedelic** [comment]
Or https://opendatacommons.org/licenses/odbl

**Comment by kawabata** [comment]
Dear Tony,

My data is derived from CHISE database (http://www.chise.org/ids-find), which distributes
the data with GPL.  The original author, Dr. Morioka-san is a vehement supporter of GPL and FSF,
and it is unlikely that the license would be changed.

With best regards,
