### ISSUE TITLE
no japanese decomposition for 懐

### ISSUE THREAD

**Issue by wareya** [cjkvi/cjkvi-ids#66]
top right grapheme is given differently

edit: this is most likely because of unihan; in japanese, the right sides of these characters are identical

**Comment by kenlunde** [comment]
When examining the regional differences in the code charts, U+58CA 壊 is okay with only ⿰土⿱十𭾱 as its IDS. However, U+61D0 懐 would benefit by having two IDS. The existing one, ⿰忄⿱亠𭾱, corresponds to the Chinese representative glyphs, but an additional one, ⿰忄⿱十𭾱, would then correspond to the Japanese and Korean representative glyphs.

(As an aside, the G-Source representative glyph for U+58CA 壊 should probably be composed as ⿰土⿱亠𭾱 to follow regional conventions, but that is a separate matter.)

**Comment by kawabata** [comment]
Thanks for your findings.  Now I've updated IDS representation of 懐.
