### ISSUE TITLE
Unify the encoding of `ws2015-ids*`

### ISSUE THREAD

**Issue by JLHwung** [cjkvi/cjkvi-ids#69]
The encoding of `ws2015-ids*` is different to other files.
```sh
$ file -I *
README.md:          text/plain; charset=utf-8
hanyo-ids.txt:      text/plain; charset=utf-8
ids-analysis.txt:   text/plain; charset=utf-8
ids-cdp.txt:        text/plain; charset=utf-8
ids-ext-cdef.txt:   text/plain; charset=utf-8
ids.txt:            text/plain; charset=utf-8
ucs-strokes.txt:    text/plain; charset=utf-8
waseikanji-ids.txt: text/plain; charset=utf-8
ws2015-ids-cdp.txt: text/plain; charset=utf-16le
ws2015-ids.txt:     text/plain; charset=utf-16le
```

The `ws2015-ids*` is encoded in `utf-16le` while the other files in `utf-8`. I suggest we convert `ws2015-ids*` to utf-8 for consistency if there is no specific reasons or conventions.

Motivation:
Personally I use `git-grep` to find the ideographs that I don't know how to pronounce. However I find the following command fails with `ws2015-ids.txt` since this file is not encoded in `utf-8`:
```sh
# grep UTC-01110 in ws2015-ids
$ git grep ⿱宗贝 -- ws2015-ids.txt
```

**Comment by kawabata** [comment]
Thanks for your comment.
I've fixed to make all of them to be UTF-8.
