### ISSUE TITLE
IDS for U+4E15 丕

### ISSUE THREAD

**Issue by 2SC1815J** [cjkvi/cjkvi-ids#70]
[ids-analysis.txt#91](https://github.com/cjkvi/cjkvi-ids/blob/master/ids-analysis.txt#L91) says
> U+04E15 丕 ⿱丕一 不聲 0010040 # 【字通】象形

[説文解字第一篇上](http://archive.wul.waseda.ac.jp/kosho/ho04/ho04_00023/ho04_00023_0001/ho04_00023_0001_p0017.jpg) says
> 大也从一不聲

Should be ⿱不一 ?

**Comment by kawabata** [comment]
Thanks!  fixed it now.
