### ISSUE TITLE
Decomposition of 𢰺 (U+22C3A) should be ⿰扌負

### ISSUE THREAD

**Issue by hfhchan** [cjkvi/cjkvi-ids#74]
Decomposition of 𢰺 (U+22C3A) should be ⿰扌負。
![image](https://user-images.githubusercontent.com/8191296/49681119-799c5000-fad7-11e8-82ae-86809597b4fc.png)

The V source is clearly 負.
The T source is pronunced fù, so it can be reasonably deduced that the right hand side is indeed 負 fù.

**Comment by kawabata** [comment]
Fixed.  Thanks!
