### ISSUE TITLE
Undifined Tag 'H', 'M', 'S', 'U'

### ISSUE THREAD

**Issue by IShengFang** [cjkvi/cjkvi-ids#77]
I can't find the definition of these tags('H', 'M', 'S' and 'U') in the encoding policies of README.md.
What are these tags mean?

Thanks

**Comment by eisoch** [comment]
In the IRG works, H=Hong Kong, M=Macau, S=Singapore, U=UTC/US or SAT. 






At 2019-02-14 22:59:49, "I-Sheng Fang" <notifications@github.com> wrote:


I can't find the definition of these tags('H', 'M', 'S' and 'U') in the encoding policies of README.md.
What are these tags mean?

Thanks

**Comment by IShengFang** [comment]
@eisoch 
Thank You :smile_cat:
